FROM debian:bookworm-slim

WORKDIR /app

# Importante: El binario se copia desde el contexto local (ya compilado por el CI)
COPY target/frontend-api /app/frontend-api
RUN chmod +x /app/frontend-api

ENV SERVER_PORT=${PORT}
ENV TZ=Europe/Madrid

RUN useradd -m springuser
USER springuser

ENTRYPOINT ["/app/frontend-api"]