# ======================================
# APP / SERVER
# ======================================
spring.application.name=frontend-api
server.port=${PORT:8084}

# ======================================
# EXTERNAL CONFIG IMPORTS
# ======================================
spring.config.import=optional:classpath:resend.properties

# ======================================
# BACKOFFICE API
# ======================================
backoffice.api.url=${BACKOFFICE_API_URL}

# ======================================
# CACHE (CAFFEINE)
# ======================================
spring.cache.type=caffeine
spring.cache.cache-names=news

# ======================================
# RESILIENCE4J - CIRCUIT BREAKER (NEWS)
# ======================================
resilience4j.circuitbreaker.instances.newsCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.newsCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.newsCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.newsCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.newsCircuitBreaker.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.newsCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.newsCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.newsCircuitBreaker.eventConsumerBufferSize=10
resilience4j.circuitbreaker.instances.newsCircuitBreaker.recordExceptions[0]=org.springframework.web.reactive.function.client.WebClientRequestException
resilience4j.circuitbreaker.instances.newsCircuitBreaker.recordExceptions[1]=org.springframework.web.reactive.function.client.WebClientResponseException
resilience4j.circuitbreaker.instances.newsCircuitBreaker.recordExceptions[2]=java.net.ConnectException
resilience4j.circuitbreaker.instances.newsCircuitBreaker.recordExceptions[3]=java.io.IOException

# ======================================
# JWT
# ======================================
jwt.secret=${JWT_SECRET}
jwt.access.expiration=${JWT_ACCESS_EXPIRATION}

# ======================================
# SUPABASE STORAGE
# ======================================
supabase.api=${SUPABASE_API_URL}
supabase.bucket=${SUPABASE_NAME}
supabase.key=${SUPABASE_KEY}